# frozen_string_literal: true

require "test_helper"

class UaPassportTest < Minitest::Test
  def test_transliteration_examples
    assert_equal "Alushta", Cyrillic.t("Алушта", :ua_passport)
    assert_equal "Andrii", Cyrillic.t("Андрій", :ua_passport)
    assert_equal "Borshchahivka", Cyrillic.t("Борщагівка", :ua_passport)
    assert_equal "Borysenko", Cyrillic.t("Борисенко", :ua_passport)
    assert_equal "Vinnytsia", Cyrillic.t("Вінниця", :ua_passport)
    assert_equal "Volodymyr", Cyrillic.t("Володимир", :ua_passport)
    assert_equal "Hadiach", Cyrillic.t("Гадяч", :ua_passport)
    assert_equal "Bohdan", Cyrillic.t("Богдан", :ua_passport)
    assert_equal "Zghurskyi", Cyrillic.t("Згурський", :ua_passport)
    assert_equal "Galagan", Cyrillic.t("Ґалаґан", :ua_passport)
    assert_equal "Gorgany", Cyrillic.t("Ґорґани", :ua_passport)
    assert_equal "Donetsk", Cyrillic.t("Донецьк", :ua_passport)
    assert_equal "Dmytro", Cyrillic.t("Дмитро", :ua_passport)
    assert_equal "Rivne", Cyrillic.t("Рівне", :ua_passport)
    assert_equal "Oleh", Cyrillic.t("Олег", :ua_passport)
    assert_equal "Esman", Cyrillic.t("Есмань", :ua_passport)
    assert_equal "Yenakiieve", Cyrillic.t("Єнакієве", :ua_passport)
    assert_equal "Haievych", Cyrillic.t("Гаєвич", :ua_passport)
    assert_equal "Koropie", Cyrillic.t("Короп'є", :ua_passport)
    assert_equal "Zhytomyr", Cyrillic.t("Житомир", :ua_passport)
    assert_equal "Zhanna", Cyrillic.t("Жанна", :ua_passport)
    assert_equal "Zhezheliv", Cyrillic.t("Жежелів", :ua_passport)
    assert_equal "Zakarpattia", Cyrillic.t("Закарпаття", :ua_passport)
    assert_equal "Kazymyrchuk", Cyrillic.t("Казимирчук", :ua_passport)
    assert_equal "Medvyn", Cyrillic.t("Медвин", :ua_passport)
    assert_equal "Mykhailenko", Cyrillic.t("Михайленко", :ua_passport)
    assert_equal "Ivankiv", Cyrillic.t("Іванків", :ua_passport)
    assert_equal "Ivashchenko", Cyrillic.t("Іващенко", :ua_passport)
    assert_equal "Yizhakevych", Cyrillic.t("Їжакевич", :ua_passport)
    assert_equal "Kadyivka", Cyrillic.t("Кадиївка", :ua_passport)
    assert_equal "Marine", Cyrillic.t("Мар'їне", :ua_passport)
    assert_equal "Yosypivka", Cyrillic.t("Йосипівка", :ua_passport)
    assert_equal "Stryi", Cyrillic.t("Стрий", :ua_passport)
    assert_equal "Oleksii", Cyrillic.t("Олексій", :ua_passport)
    assert_equal "Kyiv", Cyrillic.t("Київ", :ua_passport)
    assert_equal "Kovalenko", Cyrillic.t("Коваленко", :ua_passport)
    assert_equal "Lebedyn", Cyrillic.t("Лебедин", :ua_passport)
    assert_equal "Leonid", Cyrillic.t("Леонід", :ua_passport)
    assert_equal "Mykolaiv", Cyrillic.t("Миколаїв", :ua_passport)
    assert_equal "Marynych", Cyrillic.t("Маринич", :ua_passport)
    assert_equal "Nizhyn", Cyrillic.t("Ніжин", :ua_passport)
    assert_equal "Nataliia", Cyrillic.t("Наталія", :ua_passport)
    assert_equal "Odesa", Cyrillic.t("Одеса", :ua_passport)
    assert_equal "Onyshchenko", Cyrillic.t("Онищенко", :ua_passport)
    assert_equal "Poltava", Cyrillic.t("Полтава", :ua_passport)
    assert_equal "Petro", Cyrillic.t("Петро", :ua_passport)
    assert_equal "Reshetylivka", Cyrillic.t("Решетилівка", :ua_passport)
    assert_equal "Rybchynskyi", Cyrillic.t("Рибчинський", :ua_passport)
    assert_equal "Sumy", Cyrillic.t("Суми", :ua_passport)
    assert_equal "Solomiia", Cyrillic.t("Соломія", :ua_passport)
    assert_equal "Ternopil", Cyrillic.t("Тернопіль", :ua_passport)
    assert_equal "Trots", Cyrillic.t("Троць", :ua_passport)
    assert_equal "Uzhhorod", Cyrillic.t("Ужгород", :ua_passport)
    assert_equal "Uliana", Cyrillic.t("Уляна", :ua_passport)
    assert_equal "Fastiv", Cyrillic.t("Фастів", :ua_passport)
    assert_equal "Filipchuk", Cyrillic.t("Філіпчук", :ua_passport)
    assert_equal "Kharkiv", Cyrillic.t("Харків", :ua_passport)
    assert_equal "Khrystyna", Cyrillic.t("Христина", :ua_passport)
    assert_equal "Bila Tserkva", Cyrillic.t("Біла Церква", :ua_passport)
    assert_equal "Stetsenko", Cyrillic.t("Стеценко", :ua_passport)
    assert_equal "Chernivtsi", Cyrillic.t("Чернівці", :ua_passport)
    assert_equal "Shevchenko", Cyrillic.t("Шевченко", :ua_passport)
    assert_equal "Shostka", Cyrillic.t("Шостка", :ua_passport)
    assert_equal "Kyshenky", Cyrillic.t("Кишеньки", :ua_passport)
    assert_equal "Shcherbukhy", Cyrillic.t("Щербухи", :ua_passport)
    assert_equal "Hoshcha", Cyrillic.t("Гоща", :ua_passport)
    assert_equal "Harashchenko", Cyrillic.t("Гаращенко", :ua_passport)
    assert_equal "Yurii", Cyrillic.t("Юрій", :ua_passport)
    assert_equal "Koriukivka", Cyrillic.t("Корюківка", :ua_passport)
    assert_equal "Yahotyn", Cyrillic.t("Яготин", :ua_passport)
    assert_equal "Yaroshenko", Cyrillic.t("Ярошенко", :ua_passport)
    assert_equal "Kostiantyn", Cyrillic.t("Костянтин", :ua_passport)
    assert_equal "Znamianka", Cyrillic.t("Знам'янка", :ua_passport)
    assert_equal "Feodosiia", Cyrillic.t("Феодосія", :ua_passport)
    assert_equal "Mykhailo", Cyrillic.t("Михайло", :ua_passport)
    assert_equal "Halyna", Cyrillic.t("Галина", :ua_passport)
    assert_equal "Viacheslav", Cyrillic.t("В'ячеслав", :ua_passport)
    assert_equal "Kyiv, vul. Khreshchatyk", Cyrillic.t("Київ, вул. Хрещатик", :ua_passport)
  end

  def test_zgh
    assert_equal "Zghorany", Cyrillic.t("Згорани", :ua_passport)
    assert_equal "Rozghon", Cyrillic.t("Розгон", :ua_passport)
  end

  def test_address
    assert_equal "vulytsia", Cyrillic.t("вулиця", :ua_passport)
    assert_equal "vul.", Cyrillic.t("вул.", :ua_passport)
    assert_equal "prospekt", Cyrillic.t("проспект", :ua_passport)
    assert_equal "prosp.", Cyrillic.t("просп.", :ua_passport)
    assert_equal "bulvar", Cyrillic.t("бульвар", :ua_passport)
    assert_equal "provulok", Cyrillic.t("провулок", :ua_passport)
    assert_equal "ploshcha", Cyrillic.t("площа", :ua_passport)
    assert_equal "budynok / kvartyra", Cyrillic.t("будинок / квартира", :ua_passport)
    assert_equal "bud. / kv.", Cyrillic.t("буд. / кв.", :ua_passport)
    assert_equal "oblast", Cyrillic.t("область", :ua_passport)
    assert_equal "raion", Cyrillic.t("район", :ua_passport)
    assert_equal "selo / selyshche", Cyrillic.t("село / селище", :ua_passport)
  end

  def test_cities
    assert_equal "Kyiv", Cyrillic.t("Київ", :ua_passport)
    assert_equal "Kharkiv", Cyrillic.t("Харків", :ua_passport)
    assert_equal "Odesa", Cyrillic.t("Одеса", :ua_passport)
    assert_equal "Dnipro", Cyrillic.t("Дніпро", :ua_passport)
    assert_equal "Donetsk", Cyrillic.t("Донецьк", :ua_passport)
    assert_equal "Zaporizhzhia", Cyrillic.t("Запоріжжя", :ua_passport)
    assert_equal "Lviv", Cyrillic.t("Львів", :ua_passport)
    assert_equal "Kryvyi Rih", Cyrillic.t("Кривий Ріг", :ua_passport)
    assert_equal "Mykolaiv", Cyrillic.t("Миколаїв", :ua_passport)
    assert_equal "Sevastopol", Cyrillic.t("Севастополь", :ua_passport)
    assert_equal "Mariupol", Cyrillic.t("Маріуполь", :ua_passport)
    assert_equal "Luhansk", Cyrillic.t("Луганськ", :ua_passport)
    assert_equal "Vinnytsia", Cyrillic.t("Вінниця", :ua_passport)
    assert_equal "Makiivka", Cyrillic.t("Макіївка", :ua_passport)
    assert_equal "Simferopol", Cyrillic.t("Сімферополь", :ua_passport)
    assert_equal "Kherson", Cyrillic.t("Херсон", :ua_passport)
    assert_equal "Poltava", Cyrillic.t("Полтава", :ua_passport)
    assert_equal "Chernihiv", Cyrillic.t("Чернігів", :ua_passport)
    assert_equal "Cherkasy", Cyrillic.t("Черкаси", :ua_passport)
    assert_equal "Zhytomyr", Cyrillic.t("Житомир", :ua_passport)
    assert_equal "Sumy", Cyrillic.t("Суми", :ua_passport)
    assert_equal "Khmelnytskyi", Cyrillic.t("Хмельницький", :ua_passport)
    assert_equal "Chernivtsi", Cyrillic.t("Чернівці", :ua_passport)
    assert_equal "Horlivka", Cyrillic.t("Горлівка", :ua_passport)
    assert_equal "Rivne", Cyrillic.t("Рівне", :ua_passport)
    assert_equal "Kamianske", Cyrillic.t("Кам'янське", :ua_passport)
    assert_equal "Kropyvnytskyi", Cyrillic.t("Кропивницький", :ua_passport)
    assert_equal "Ivano-Frankivsk", Cyrillic.t("Івано-Франківськ", :ua_passport)
    assert_equal "Kremenchuk", Cyrillic.t("Кременчук", :ua_passport)
    assert_equal "Ternopil", Cyrillic.t("Тернопіль", :ua_passport)
    assert_equal "Lutsk", Cyrillic.t("Луцьк", :ua_passport)
    assert_equal "Bila Tserkva", Cyrillic.t("Біла Церква", :ua_passport)
    assert_equal "Kramatorsk", Cyrillic.t("Краматорськ", :ua_passport)
    assert_equal "Melitopol", Cyrillic.t("Мелітополь", :ua_passport)
    assert_equal "Kerch", Cyrillic.t("Керч", :ua_passport)
    assert_equal "Nikopol", Cyrillic.t("Нікополь", :ua_passport)
    assert_equal "Berdiansk", Cyrillic.t("Бердянськ", :ua_passport)
    assert_equal "Sloviansk", Cyrillic.t("Слов'янськ", :ua_passport)
    assert_equal "Uzhhorod", Cyrillic.t("Ужгород", :ua_passport)
    assert_equal "Alchevsk", Cyrillic.t("Алчевськ", :ua_passport)
    assert_equal "Pavlohrad", Cyrillic.t("Павлоград", :ua_passport)
    assert_equal "Sievierodonetsk", Cyrillic.t("Сєвєродонецьк", :ua_passport)
    assert_equal "Yevpatoriia", Cyrillic.t("Євпаторія", :ua_passport)
    assert_equal "Lysychansk", Cyrillic.t("Лисичанськ", :ua_passport)
    assert_equal "Kamianets-Podilskyi", Cyrillic.t("Кам'янець-Подільський", :ua_passport)
    assert_equal "Brovary", Cyrillic.t("Бровари", :ua_passport)
    assert_equal "Mukachevo", Cyrillic.t("Мукачево", :ua_passport)
    assert_equal "Yalta", Cyrillic.t("Ялта", :ua_passport)
    assert_equal "Uman", Cyrillic.t("Умань", :ua_passport)
    assert_equal "Berdychiv", Cyrillic.t("Бердичів", :ua_passport)
    assert_equal "Drohobych", Cyrillic.t("Дрогобич", :ua_passport)
    assert_equal "Izmail", Cyrillic.t("Ізмаїл", :ua_passport)
    assert_equal "Irpin", Cyrillic.t("Ірпінь", :ua_passport)
    assert_equal "Kolomyia", Cyrillic.t("Коломия", :ua_passport)
    assert_equal "Stryi", Cyrillic.t("Стрий", :ua_passport)
    assert_equal "Kovel", Cyrillic.t("Ковель", :ua_passport)
    assert_equal "Kalush", Cyrillic.t("Калуш", :ua_passport)
    assert_equal "Nizhyn", Cyrillic.t("Ніжин", :ua_passport)
    assert_equal "Novohrad-Volynskyi", Cyrillic.t("Новоград-Волинський", :ua_passport)
    assert_equal "Shostka", Cyrillic.t("Шостка", :ua_passport)
    assert_equal "Pryluky", Cyrillic.t("Прилуки", :ua_passport)
    assert_equal "Lozova", Cyrillic.t("Лозова", :ua_passport)
    assert_equal "Konotop", Cyrillic.t("Конотоп", :ua_passport)
    assert_equal "Bakhmut", Cyrillic.t("Бахмут", :ua_passport)
    assert_equal "Pervomaisk", Cyrillic.t("Первомайськ", :ua_passport)
    assert_equal "Chervonohrad", Cyrillic.t("Червоноград", :ua_passport)
    assert_equal "Druzhkivka", Cyrillic.t("Дружківка", :ua_passport)
    assert_equal "Enerhodar", Cyrillic.t("Енергодар", :ua_passport)
    assert_equal "Voznesensk", Cyrillic.t("Вознесенськ", :ua_passport)
    assert_equal "Novovolynsk", Cyrillic.t("Нововолинськ", :ua_passport)
    assert_equal "Znamianka", Cyrillic.t("Знам'янка", :ua_passport)
    assert_equal "Fastiv", Cyrillic.t("Фастів", :ua_passport)
    assert_equal "Obukhiv", Cyrillic.t("Обухів", :ua_passport)
    assert_equal "Boryslav", Cyrillic.t("Борислав", :ua_passport)
    assert_equal "Truskavets", Cyrillic.t("Трускавець", :ua_passport)
    assert_equal "Morshyn", Cyrillic.t("Моршин", :ua_passport)
    assert_equal "Yaremche", Cyrillic.t("Яремче", :ua_passport)
    assert_equal "Boryspil", Cyrillic.t("Бориспіль", :ua_passport)
    assert_equal "Vasylkiv", Cyrillic.t("Васильків", :ua_passport)
    assert_equal "Pereiaslav", Cyrillic.t("Переяслав", :ua_passport)
    assert_equal "Bohuslav", Cyrillic.t("Богуслав", :ua_passport)
    assert_equal "Rzhyshchiv", Cyrillic.t("Ржищів", :ua_passport)
    assert_equal "Ukrainka", Cyrillic.t("Українка", :ua_passport)
    assert_equal "Slavutych", Cyrillic.t("Славутич", :ua_passport)
    assert_equal "Vyshhorod", Cyrillic.t("Вишгород", :ua_passport)
  end

  def test_regions
    assert_equal "Vinnytska oblast", Cyrillic.t("Вінницька область", :ua_passport)
    assert_equal "Volynska oblast", Cyrillic.t("Волинська область", :ua_passport)
    assert_equal "Dnipropetrovska oblast", Cyrillic.t("Дніпропетровська область", :ua_passport)
    assert_equal "Donetska oblast", Cyrillic.t("Донецька область", :ua_passport)
    assert_equal "Zhytomyrska oblast", Cyrillic.t("Житомирська область", :ua_passport)
    assert_equal "Zakarpatska oblast", Cyrillic.t("Закарпатська область", :ua_passport)
    assert_equal "Zaporizka oblast", Cyrillic.t("Запорізька область", :ua_passport)
    assert_equal "Ivano-Frankivska oblast", Cyrillic.t("Івано-Франківська область", :ua_passport)
    assert_equal "Kyivska oblast", Cyrillic.t("Київська область", :ua_passport)
    assert_equal "Kirovohradska oblast", Cyrillic.t("Кіровоградська область", :ua_passport)
    assert_equal "Luhanska oblast", Cyrillic.t("Луганська область", :ua_passport)
    assert_equal "Lvivska oblast", Cyrillic.t("Львівська область", :ua_passport)
    assert_equal "Mykolaivska oblast", Cyrillic.t("Миколаївська область", :ua_passport)
    assert_equal "Odeska oblast", Cyrillic.t("Одеська область", :ua_passport)
    assert_equal "Poltavska oblast", Cyrillic.t("Полтавська область", :ua_passport)
    assert_equal "Rivnenska oblast", Cyrillic.t("Рівненська область", :ua_passport)
    assert_equal "Sumska oblast", Cyrillic.t("Сумська область", :ua_passport)
    assert_equal "Ternopilska oblast", Cyrillic.t("Тернопільська область", :ua_passport)
    assert_equal "Kharkivska oblast", Cyrillic.t("Харківська область", :ua_passport)
    assert_equal "Khersonska oblast", Cyrillic.t("Херсонська область", :ua_passport)
    assert_equal "Khmelnytska oblast", Cyrillic.t("Хмельницька область", :ua_passport)
    assert_equal "Cherkaska oblast", Cyrillic.t("Черкаська область", :ua_passport)
    assert_equal "Chernivetska oblast", Cyrillic.t("Чернівецька область", :ua_passport)
    assert_equal "Chernihivska oblast", Cyrillic.t("Чернігівська область", :ua_passport)
  end
end
