require "test_helper"

class UaPassportTest < Minitest::Test
  def test_transliteration_examples
    assert_equal "Alushta", Cyrillic.t("Алушта", :ua_passport)
    assert_equal "Andrii", Cyrillic.t("Андрій", :ua_passport)
    assert_equal "Borshchahivka", Cyrillic.t("Борщагівка", :ua_passport)
    assert_equal "Borysenko", Cyrillic.t("Борисенко", :ua_passport)
    assert_equal "Vinnytsia", Cyrillic.t("Вінниця", :ua_passport)
    assert_equal "Volodymyr", Cyrillic.t("Володимир", :ua_passport)
    assert_equal "Hadiach", Cyrillic.t("Гадяч", :ua_passport)
    assert_equal "Bohdan", Cyrillic.t("Богдан", :ua_passport)
    assert_equal "Zghurskyi", Cyrillic.t("Згурський", :ua_passport)
    assert_equal "Galagan", Cyrillic.t("Ґалаґан", :ua_passport)
    assert_equal "Gorgany", Cyrillic.t("Ґорґани", :ua_passport)
    assert_equal "Donetsk", Cyrillic.t("Донецьк", :ua_passport)
    assert_equal "Dmytro", Cyrillic.t("Дмитро", :ua_passport)
    assert_equal "Rivne", Cyrillic.t("Рівне", :ua_passport)
    assert_equal "Oleh", Cyrillic.t("Олег", :ua_passport)
    assert_equal "Esman", Cyrillic.t("Есмань", :ua_passport)
    assert_equal "Yenakiieve", Cyrillic.t("Єнакієве", :ua_passport)
    assert_equal "Haievych", Cyrillic.t("Гаєвич", :ua_passport)
    assert_equal "Koropie", Cyrillic.t("Короп'є", :ua_passport)
    assert_equal "Zhytomyr", Cyrillic.t("Житомир", :ua_passport)
    assert_equal "Zhanna", Cyrillic.t("Жанна", :ua_passport)
    assert_equal "Zhezheliv", Cyrillic.t("Жежелів", :ua_passport)
    assert_equal "Zakarpattia", Cyrillic.t("Закарпаття", :ua_passport)
    assert_equal "Kazymyrchuk", Cyrillic.t("Казимирчук", :ua_passport)
    assert_equal "Medvyn", Cyrillic.t("Медвин", :ua_passport)
    assert_equal "Mykhailenko", Cyrillic.t("Михайленко", :ua_passport)
    assert_equal "Ivankiv", Cyrillic.t("Іванків", :ua_passport)
    assert_equal "Ivashchenko", Cyrillic.t("Іващенко", :ua_passport)
    assert_equal "Yizhakevych", Cyrillic.t("Їжакевич", :ua_passport)
    assert_equal "Kadyivka", Cyrillic.t("Кадиївка", :ua_passport)
    assert_equal "Marine", Cyrillic.t("Мар'їне", :ua_passport)
    assert_equal "Yosypivka", Cyrillic.t("Йосипівка", :ua_passport)
    assert_equal "Stryi", Cyrillic.t("Стрий", :ua_passport)
    assert_equal "Oleksii", Cyrillic.t("Олексій", :ua_passport)
    assert_equal "Kyiv", Cyrillic.t("Київ", :ua_passport)
    assert_equal "Kovalenko", Cyrillic.t("Коваленко", :ua_passport)
    assert_equal "Lebedyn", Cyrillic.t("Лебедин", :ua_passport)
    assert_equal "Leonid", Cyrillic.t("Леонід", :ua_passport)
    assert_equal "Mykolaiv", Cyrillic.t("Миколаїв", :ua_passport)
    assert_equal "Marynych", Cyrillic.t("Маринич", :ua_passport)
    assert_equal "Nizhyn", Cyrillic.t("Ніжин", :ua_passport)
    assert_equal "Nataliia", Cyrillic.t("Наталія", :ua_passport)
    assert_equal "Odesa", Cyrillic.t("Одеса", :ua_passport)
    assert_equal "Onyshchenko", Cyrillic.t("Онищенко", :ua_passport)
    assert_equal "Poltava", Cyrillic.t("Полтава", :ua_passport)
    assert_equal "Petro", Cyrillic.t("Петро", :ua_passport)
    assert_equal "Reshetylivka", Cyrillic.t("Решетилівка", :ua_passport)
    assert_equal "Rybchynskyi", Cyrillic.t("Рибчинський", :ua_passport)
    assert_equal "Sumy", Cyrillic.t("Суми", :ua_passport)
    assert_equal "Solomiia", Cyrillic.t("Соломія", :ua_passport)
    assert_equal "Ternopil", Cyrillic.t("Тернопіль", :ua_passport)
    assert_equal "Trots", Cyrillic.t("Троць", :ua_passport)
    assert_equal "Uzhhorod", Cyrillic.t("Ужгород", :ua_passport)
    assert_equal "Uliana", Cyrillic.t("Уляна", :ua_passport)
    assert_equal "Fastiv", Cyrillic.t("Фастів", :ua_passport)
    assert_equal "Filipchuk", Cyrillic.t("Філіпчук", :ua_passport)
    assert_equal "Kharkiv", Cyrillic.t("Харків", :ua_passport)
    assert_equal "Khrystyna", Cyrillic.t("Христина", :ua_passport)
    assert_equal "Bila Tserkva", Cyrillic.t("Біла Церква", :ua_passport)
    assert_equal "Stetsenko", Cyrillic.t("Стеценко", :ua_passport)
    assert_equal "Chernivtsi", Cyrillic.t("Чернівці", :ua_passport)
    assert_equal "Shevchenko", Cyrillic.t("Шевченко", :ua_passport)
    assert_equal "Shostka", Cyrillic.t("Шостка", :ua_passport)
    assert_equal "Kyshenky", Cyrillic.t("Кишеньки", :ua_passport)
    assert_equal "Shcherbukhy", Cyrillic.t("Щербухи", :ua_passport)
    assert_equal "Hoshcha", Cyrillic.t("Гоща", :ua_passport)
    assert_equal "Harashchenko", Cyrillic.t("Гаращенко", :ua_passport)
    assert_equal "Yurii", Cyrillic.t("Юрій", :ua_passport)
    assert_equal "Koriukivka", Cyrillic.t("Корюківка", :ua_passport)
    assert_equal "Yahotyn", Cyrillic.t("Яготин", :ua_passport)
    assert_equal "Yaroshenko", Cyrillic.t("Ярошенко", :ua_passport)
    assert_equal "Kostiantyn", Cyrillic.t("Костянтин", :ua_passport)
    assert_equal "Znamianka", Cyrillic.t("Знам'янка", :ua_passport)
    assert_equal "Feodosiia", Cyrillic.t("Феодосія", :ua_passport)
  end

  def test_zgh
    assert_equal "Zghorany", Cyrillic.t("Згорани", :ua_passport)
    assert_equal "Rozghon", Cyrillic.t("Розгон", :ua_passport)
  end
end
