#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"
require "cyrillic"

scheme = nil
reverse = false

parser = OptionParser.new do |opts|
  opts.banner = "Usage: cyrillic [options] [text | file...]"
  opts.separator ""
  opts.separator "Transliterate Cyrillic script to Roman (Latin) script, or reverse with -r."
  opts.separator ""
  opts.separator "Examples:"
  opts.separator "  cyrillic 'Кириллица'"
  opts.separator "  echo 'Кириллица' | cyrillic"
  opts.separator "  cyrillic -r 'Transliteraciâ'"
  opts.separator "  cyrillic -s serbian 'Љубљана'"
  opts.separator "  cyrillic -r -s serbian 'Ljubljana'"
  opts.separator "  cyrillic -r -s gost779b 'Shhuka'"
  opts.separator ""
  opts.separator "Options:"

  schemes = %w[default cyrillic iso9 mongolian ukrainian ua_passport de serbian gost779b bgn_pcgn bulgarian belarusian]
  opts.on("-s", "--scheme SCHEME", schemes,
          "Transliteration scheme (#{schemes.join(', ')})") do |s|
    scheme = s == "default" ? nil : s.to_sym
  end

  opts.on("-r", "--reverse", "Reverse transliteration (Latin to Cyrillic)") do
    reverse = true
  end

  opts.on("-v", "--version", "Show version") do
    puts "cyrillic #{Cyrillic::VERSION}"
    exit
  end

  opts.on("-h", "--help", "Show this help message") do
    puts opts
    exit
  end
end

parser.parse!

process = lambda do |text|
  if reverse
    Cyrillic.detransliterate(text, from: scheme || :iso9)
  else
    Cyrillic.transliterate(text, scheme || :cyrillic)
  end
end

if ARGV.empty?
  if $stdin.tty?
    puts parser
    exit 1
  else
    $stdin.each_line do |line|
      puts process.call(line.chomp)
    end
  end
else
  ARGV.each do |arg|
    if File.file?(arg)
      File.foreach(arg) do |line|
        puts process.call(line.chomp)
      end
    else
      puts process.call(arg)
    end
  end
end
